### ISSUE TITLE
Change of geometry interface

### ISSUE THREAD

**Issue by evenmn** [henriasv/molecular-builder#10]
Even though the geometry class works perfectly fine as it is, I would like to suggest some changes that may makes it more user-friendly. For instance, the BoxGeometry takes the arguments 'center' and 'length'. However, usually the lower corner (xlo, ylo, zlo) is located at origin which makes the 'center' argument a bit excessive. Instead of taking 'center' and 'length' as arguments, my suggestion is to take lower and upper corner as arguments. The same idea can be applied to CubeGeometry and perhaps CylinderGeometry.

**Comment by henriasv** [comment]
For the Boxgeometry I agree. For the CubeGeometry and cylinder geometry i suggest keeping center, length ets. I expect our usage will be such that center-interface is easier to use.

**Comment by evenmn** [comment]
When changing BoxGeometry, pack_water also needs to be updated as BoxGeometry is its default geometry. Furthermore, the BlockGeometry can safely be removed as the PlaneGeometry now supports any [polyhedron](https://en.wikipedia.org/wiki/Polyhedron) (thetrahedrons, parallel epipeds, as well as cubes and [rhombicuboctahedrons](https://en.wikipedia.org/wiki/Rhombicuboctahedron)). PlaneGeometry might also replace the PlaneBoundTriclinicGeometry class, but its strength is that it takes the cell as argument.

**Comment by henriasv** [comment]
Maybe we can support both (center, length) and (lo, hi) with keyword arguments. There are good arguments for both, and much bepends om how it is being used. E.g. if you want to carve out a collection og random boxes in a structure, i suppose center-length is better, whereas for putting something in the lower left inner corner of a box, lo-hi is better. I think I want to keep BlockGeometry, but maybe it can now be a subclass of PlaneGeometry. It becomes easier to read what kind if system a piece of code is creating if the interface is very explicit.

**Comment by evenmn** [comment]
That's a good idea! We can keep BlockGeometry, but we should rename it. I find the name rather confusing, as we already have CubeGeometry and BoxGeometry. BlockGeometry was implemented to carve out boxes and parallelepipeds.
