### ISSUE TITLE
Amorphous silica data files on Zenodo damaged?

### ISSUE THREAD

**Issue by evenmn** [henriasv/molecular-builder#6]
I am not able to read the amorphous silica data files on Zenodo using ase.io.read. It seems to be some unexpected numbers of objects in the files. I have tried both "amorphous_silica_1" and "amorphous_silica_p3754", but the same error message occurs.

**Comment by henriasv** [comment]
This is an ase error due to an if/elif typo in the lammps data file reader. It seems like it has been resolved, and will be OK in the next version of ase. For now, you can edit line 205 from if to elif in ase/io/lammpsdata.py
